# Generated by Django 2.2.3 on 2019-07-14 13:19
from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'users.json', app_label='parser_app')

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(load_fixture)
    ]
