# Generated by Django 2.2.3 on 2019-07-17 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parser_app', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField()),
                ('D1', models.CharField(blank=True, max_length=8)),
                ('D2', models.CharField(blank=True, max_length=8)),
                ('D3', models.CharField(blank=True, max_length=8)),
                ('D4', models.CharField(blank=True, max_length=8)),
                ('D5', models.CharField(blank=True, max_length=8)),
                ('D6', models.CharField(blank=True, max_length=8)),
                ('D7', models.CharField(blank=True, max_length=8)),
                ('D8', models.CharField(blank=True, max_length=8)),
                ('D9', models.CharField(blank=True, max_length=8)),
                ('D10', models.CharField(blank=True, max_length=8)),
                ('D11', models.CharField(blank=True, max_length=8)),
                ('D12', models.CharField(blank=True, max_length=8)),
                ('D13', models.CharField(blank=True, max_length=8)),
                ('D14', models.CharField(blank=True, max_length=8)),
                ('D15', models.CharField(blank=True, max_length=8)),
                ('D16', models.CharField(blank=True, max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.AddIndex(
            model_name='variable',
            index=models.Index(fields=['user', 'created_at'], name='parser_app__user_id_b943b7_idx'),
        ),
    ]
